[package]
name = "hello_web_server"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "1.12.0",features = ["attributes"] }
futures = "0.3.30"
