[lib]
proc-macro = true

[package]
name = "hello_macro_derive"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.71"
quote = "1.0"
